"""init check

Revision ID: ddb36b25930a
Revises:
Create Date: 2023-06-21 19:15:03.709084

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ddb36b25930a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.INTEGER(), nullable=False),
                    sa.Column('username', sa.VARCHAR(length=32), nullable=True),
                    sa.Column('reg_date', sa.DATE(), nullable=True),
                    sa.Column('upd_date', sa.DATE(), nullable=True),
                    sa.PrimaryKeyConstraint('user_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
